name: identity-center

services:
  identity-center-backend:
    container_name: identity-center-backend
    image: identity-center-backend:${APP_SERVER_VERSION:-latest}
    env_file:
      - path: .env
        format: raw
    environment:
      SERVER_PORT: "8080"
    volumes:
      - ./data:/data
    expose:
      - "8080"

  identity-center-frontend:
    container_name: identity-center-frontend
    image: identity-center-frontend:${APP_SERVER_VERSION:-latest}
    depends_on:
      - identity-center-backend
    ports:
      - "${FRONTEND_PORT:-11950}:80"
