services:
  identity-center-backend:
    image: identity-center-backend
    restart: unless-stopped
    build:
      context: ./backend
    container_name: identity-center-backend
    env_file:
      - ./.env
    environment:
      SERVER_PORT: "8080"
    volumes:
      - ./data:/data
    expose:
      - "8080"
    networks:
      identity-center-network:
        aliases:
          - identity-center-backend

  identity-center-frontend:
    image: identity-center-frontend
    restart: unless-stopped
    build:
      context: ./frontend
    container_name: identity-center-frontend
    depends_on:
      - identity-center-backend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      identity-center-network:
        aliases:
          - identity-center-frontend

networks:
  identity-center-network:
    external: true
